Vagrant.configure(2) do |config|
    config.vm.hostname = "centos"
    config.vm.box = "bento/centos-7.5"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
        vb.name = "centos"
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
        vb.customize ["modifyvm", :id, "--vram", "32"]
        vb.customize ["modifyvm", :id, "--natnet1", "192.168.10/24"]
        # Xenial COM1 port logging
        vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
        vb.customize ["storageattach", :id, "--storagectl", "SATA Controller",
                                            "--port", "0",
                                            "--nonrotational", "on"]
    end
    config.vm.box_check_update = true
    config.vm.graceful_halt_timeout = 180
    config.vm.synced_folder "../", "/home/vagrant/git-repo",
                            owner: 'vagrant', group: 'vagrant', automount: true
    config.ssh.forward_x11 = true
    config.ssh.forward_agent = true

    config.vm.provision "shell", inline: "cd /home/vagrant/git-repo/; ./prereqs.sh", privileged: false
end
