#!/usr/bin/env bash

# Create ubuntu user
useradd -d /home/ubuntu -p "openstack" -U -s /bin/bash -G adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev ubuntu
cp -ar /etc/skel/.[!.]* /home/ubuntu
chown -R ubuntu:ubuntu /home/ubuntu
echo "ubuntu:openstack" | chpasswd

# Compile firefox places
(cd /home/ubuntu/.mozilla/firefox/profile && sqlite3 places.sqlite < places.sql)
chown -R ubuntu:ubuntu /home/ubuntu

# Enable shared folder access
adduser ubuntu vboxsf

# Set devstack repos acces
chown -R ubuntu:ubuntu /opt/devstack
chown -R ubuntu:ubuntu /opt/stack


